#!/usr/bin/env bash

# Check if a directory is provided as an argument
if [[ $# -eq 1 ]]; then
  selected=$1
else
  # Use fzf to select a directory
  selected=$(find ~/Projects ~/Projects/datil -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# If no directory is selected, exit
if [[ -z $selected ]]; then
  return 0 # Use 'return' instead of 'exit' to avoid closing the shell
fi

# Change to the selected directory
cd "$selected" || return

# Open Neovim in the selected directory
nvim .
